// mutations.js
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_USER_PASS = 'SET_USER_PASS';
export const SET_PROJECTS = 'SET_PROJECTS';
export const SET_CURRENT_PROJECT_CODE = 'SET_CURRENT_PROJECT_CODE';
export const SET_CURRENT_CHAPTER_COODE = 'SET_CURRENT_CHAPTER_COODE';
export const SET_CURRENT_ENTRY_CODE = 'SET_CURRENT_ENTRY_CODE';
export const SET_DATE_OF_WORK = 'SET_DATE_OF_WORK';
export const SET_WORKERS_LIST = 'SET_WORKERS_LIST';
export const SET_WORKERS_LIST_BIG = 'SET_WORKERS_LIST_BIG';
export const SET_HOURS_TYPE = 'SET_HOURS_TYPE';
export const SET_HOURS = 'SET_HOURS';
export const SET_COMMENTS = 'SET_COMMENTS';
export const SET_HISTORY = 'SET_HISTORY';
export const SET_CAUSES_LIST = 'SET_CAUSES_LIST';